### ISSUE TITLE
Test checklist

### ISSUE THREAD

**Issue by shane935** [BlueChilli/ChilliSource.Web.Forms#1]
A quick brainstorm of tests we should have

### Inputs
- [ ] Value is fixed can't be overridden by user input
- [x] All attributes work (getAttributes)
- [x] onChange and onBlur are applied
- [x] [] Groups inputs
- [ ] Value is used for 

### Performance Wrapper
- [x] Applies defaultValue

### Input Group
- [x] Input group appends and prepends

### Fieldset
- [x] Fieldset correctly namespaces things

### Validation
- [ ] Validation runs
- [ ] Validation only show while invalid and blurred

### Form
- [ ] Forms only submit with valid inputs

### All
- [ ] Rerenders only when required
- [ ] No ES6 objects
